//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersData
    {
        public int Order_Id { get; set; }
        public Nullable<System.DateTime> Date_In { get; set; }
        public Nullable<bool> Status_order { get; set; }
        public int floor_id { get; set; }
        public string Floor_num { get; set; }
        public string Room_Id { get; set; }
        public int Cus_id { get; set; }
        public string fristname { get; set; }
        public string lastname { get; set; }
        public string telephone { get; set; }
        public string LineID { get; set; }
        public string Username { get; set; }
        public int CateRoom_id { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
