// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Backend.Models.Data
{
    public partial class CategoryRoom
    {
        public CategoryRoom()
        {
            CateImage = new HashSet<CateImage>();
            Room = new HashSet<Room>();
        }

        public int CateRoomId { get; set; }
        public int? Price { get; set; }
        public string CateRoomName { get; set; }
        public string Description { get; set; }

        public virtual ICollection<CateImage> CateImage { get; set; }
        public virtual ICollection<Room> Room { get; set; }
    }
}