// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Backend.Models.Data
{
    public partial class Orders
    {
        public Orders()
        {
            Payment = new HashSet<Payment>();
            ReportProblem = new HashSet<ReportProblem>();
            RoomBill = new HashSet<RoomBill>();
        }

        public int OrderId { get; set; }
        public int? CusId { get; set; }
        public DateTime? DateIn { get; set; }
        public bool? StatusOrder { get; set; }
        public string RoomId { get; set; }

        public virtual Customer Cus { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual ICollection<ReportProblem> ReportProblem { get; set; }
        public virtual ICollection<RoomBill> RoomBill { get; set; }
    }
}