// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Backend.Models.Data
{
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public int? PaymentOrderId { get; set; }
        public DateTime? PaymentDate { get; set; }
        public string PaymentPic { get; set; }
        public bool? StatusPay { get; set; }

        public virtual Orders PaymentOrder { get; set; }
    }
}