// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Backend.Models.Data
{
    public partial class ReportProblem
    {
        public int ProblemId { get; set; }
        public string ProblemText { get; set; }
        public int? OrderId { get; set; }

        public virtual Orders Order { get; set; }
    }
}