// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Backend.Models.Data
{
    public partial class RoomBill
    {
        public RoomBill()
        {
            PaymentBill = new HashSet<PaymentBill>();
        }

        public int RoomBillId { get; set; }
        public int? OrderId { get; set; }
        public int? Water { get; set; }
        public int? Electricity { get; set; }
        public int? Total { get; set; }
        public DateTime? BillDate { get; set; }
        public bool? StatusBill { get; set; }

        public virtual Orders Order { get; set; }
        public virtual ICollection<PaymentBill> PaymentBill { get; set; }
    }
}